[project]
name = "pii-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioredis==2.0.1",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.12.0",
    "async-timeout==5.0.1",
    "blis==1.3.3",
    "catalogue==2.0.10",
    "certifi==2025.11.12",
    "cffi==2.0.0",
    "charset-normalizer==3.4.4",
    "click==8.3.1",
    "cloudpathlib==0.23.0",
    "confection==0.1.5",
    "cryptography==44.0.3",
    "cymem==2.0.13",
    "fakeredis>=2.21.0",
    "fastapi==0.128.0",
    "filelock==3.20.1",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.11",
    "jinja2==3.1.6",
    "markupsafe==3.0.3",
    "matplotlib>=3.8.0",
    "murmurhash==1.0.15",
    "numpy>=2.4.0",
    "packaging==25.0",
    "pandas>=2.2.0",
    "phonenumbers==9.0.21",
    "pip==24.3.1",
    "preshed==3.0.12",
    "presidio-analyzer==2.2.360",
    "presidio-anonymizer==2.2.360",
    "prometheus-client==0.23.1",
    "pycparser==2.23",
    "pydantic==2.12.5",
    "pydantic-core==2.41.5",
    "pydantic-settings>=2.1.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "pytest-cov>=4.1.0",
    "pyyaml==6.0.3",
    "redis==7.1.0",
    "regex==2025.11.3",
    "requests==2.32.5",
    "requests-file==3.0.1",
    "respx>=0.20.0",
    "scikit-learn>=1.4.0",
    "seaborn>=0.13.0",
    "setuptools==80.9.0",
    "smart-open==7.5.0",
    "spacy==3.8.11",
    "spacy-legacy==3.0.12",
    "spacy-loggers==1.0.5",
    "srsly==2.5.2",
    "starlette==0.50.0",
    "thinc==8.3.10",
    "tldextract==5.3.0",
    "tqdm==4.67.1",
    "typer-slim==0.21.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.6.2",
    "uvicorn==0.40.0",
    "wasabi==1.1.3",
    "weasel==0.4.3",
    "wrapt==2.0.1",
]
